name: Bug Report
description: Report bugs to improve security, stability and usability
title: "Bug Report"
labels: ["bug"]

assignees: []

body:
  - type: textarea
    id: info_and_expected_outcome
    attributes:
      label: "General information"
      description: |
        Describe the bug and the expected outcome.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: |
        Please provide a short list of steps you need to do to reproduce the issue.
      placeholder: |
        1. Join the server [...]
        2. ...
    validations:
      required: true

  - type: textarea
    id: sonar_dump
    attributes:
      label: "Sonar dump"
      description: "Please provide the output of the command /sonar dump"
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional information"
      description: |
        Is there any additional information you would like to provide?
    validations:
      required: false
